//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//   /****************************************************************\
//   *  ebnf.ebnf: a self describing grammar for describing grammars  *
//   *   by codewitch honey crisis, july 2019                         *
//   \****************************************************************/
//   
//   grammar<start>= productions;
//   
//   //
//   // productions
//   //
//   // marking a non-terminal with collapse removes it from 
//   // the tree and propagates its children to its parent
//   // marking a terminal with it similarly hides it from
//   // the result but not from the grammar, unlike hidden
//   //
//   productions<collapsed> = production productions | production;
//   production= identifier [ "<" attributes ">" ] "=" expressions ";";
//   
//   //
//   // expressions
//   //
//   expressions<collapsed>= expression "|" expressions | expression;
//   expression= { symbol }+ |;
//   symbol= literal | regex | identifier | 
//   	"(" expressions ")" | 
//   	"[" expressions "]" |
//   	"{" expressions ("}"|"}+");
//   
//   //
//   // attributes
//   //
//   // recognized attributes are hidden, collapsed, terminal, start, 
//   // followsConflict (which can be "error", "first" or "last")
//   // and blockEnd (string)
//   attributes<collapsed>= attribute "," attributes | attribute;
//   attribute<color="darkRed">= identifier [ "=" attrvalue ];
//   attrvalue<color="brown">= literal | integer | identifier;
//   
//   //
//   // terminals
//   //
//   literal<color="blue">= '"([^"\\]|\\.)*"';
//   regex<color="purple">= '\'([^\'\\]|\\.)*\'';
//   identifier= '[A-Z_a-z][\-0-9A-Z_a-z]*';
//   integer<color="darkBlue">= '\-?[0-9]+';
//   
//   // hide comments and whitespace
//   //
//   // if you mark a production with the terminal attribute, you
//   // can use ebnf to define it. Anything that's text or regex 
//   // is automatically a terminal
//   whitespace<hidden,terminal>= {" "|"\v"|"\f"|"\t"|"\r"|"\n"}+; //'[ \v\f\t\r\n]+';
//   // single quotes denote regex. make sure to escape single
//   // quotes in the regex with \'
//   // attributes get passed through to the parser, and you can define your own
//   lineComment<hidden,color="green">= '//[^\n]*[\n]';
//   blockComment<hidden,blockEnd="*/",color="green">= "/*";
//   
//   // defining these isn't required, but gives
//   // us better constant names
//   // double quotes denote a literal. the escapes are nearly the
//   // same as C#. \U and \x are not supported
//   or="|";
//   lt="<";
//   gt=">";
//   eq="=";
//   semi=";";
//   comma=",";
//   lparen="(";
//   rparen=")";
//   lbracket="[";
//   rbracket="]";
//   lbrace="{";
//   rbrace="}";
//   rbracePlus="}+";
namespace LL {
    
    public class EbnfTokenizer : LL.TableTokenizer {
        public const int literal = 17;
        public const int regex = 18;
        public const int identifier = 19;
        public const int lparen = 20;
        public const int rparen = 21;
        public const int lbracket = 22;
        public const int rbracket = 23;
        public const int integer = 24;
        public const int lt = 25;
        public const int gt = 26;
        public const int eq = 27;
        public const int semi = 28;
        public const int or = 29;
        public const int lbrace = 30;
        public const int rbrace = 31;
        public const int rbracePlus = 32;
        public const int comma = 33;
        public const int whitespace = 34;
        public const int lineComment = 35;
        public const int blockComment = 36;
        public const int _EOS = 37;
        public const int _ERROR = 38;
        static string[] _Symbols = new string[] {
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                "literal",
                "regex",
                "identifier",
                "lparen",
                "rparen",
                "lbracket",
                "rbracket",
                "integer",
                "lt",
                "gt",
                "eq",
                "semi",
                "or",
                "lbrace",
                "rbrace",
                "rbracePlus",
                "comma",
                "whitespace",
                "lineComment",
                "blockComment",
                "#EOS",
                "#ERROR"};
        static string[] _BlockEnds = new string[] {
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                "*/",
                null,
                null};
        static System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>[] _DfaTable = new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>[] {
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(-1, new System.Collections.Generic.KeyValuePair<string, int>[] {
                            new System.Collections.Generic.KeyValuePair<string, int>("\"\"", 1),
                            new System.Collections.Generic.KeyValuePair<string, int>("\'\'", 6),
                            new System.Collections.Generic.KeyValuePair<string, int>("AZ__az", 11),
                            new System.Collections.Generic.KeyValuePair<string, int>("--", 13),
                            new System.Collections.Generic.KeyValuePair<string, int>("09", 14),
                            new System.Collections.Generic.KeyValuePair<string, int>("  ", 15),
                            new System.Collections.Generic.KeyValuePair<string, int>("", 16),
                            new System.Collections.Generic.KeyValuePair<string, int>("", 17),
                            new System.Collections.Generic.KeyValuePair<string, int>("\t\t", 18),
                            new System.Collections.Generic.KeyValuePair<string, int>("\r\r", 19),
                            new System.Collections.Generic.KeyValuePair<string, int>("\n\n", 20),
                            new System.Collections.Generic.KeyValuePair<string, int>("//", 21),
                            new System.Collections.Generic.KeyValuePair<string, int>("||", 26),
                            new System.Collections.Generic.KeyValuePair<string, int>("<<", 27),
                            new System.Collections.Generic.KeyValuePair<string, int>(">>", 28),
                            new System.Collections.Generic.KeyValuePair<string, int>("==", 29),
                            new System.Collections.Generic.KeyValuePair<string, int>(";;", 30),
                            new System.Collections.Generic.KeyValuePair<string, int>(",,", 31),
                            new System.Collections.Generic.KeyValuePair<string, int>("((", 32),
                            new System.Collections.Generic.KeyValuePair<string, int>("))", 33),
                            new System.Collections.Generic.KeyValuePair<string, int>("[[", 34),
                            new System.Collections.Generic.KeyValuePair<string, int>("]]", 35),
                            new System.Collections.Generic.KeyValuePair<string, int>("{{", 36),
                            new System.Collections.Generic.KeyValuePair<string, int>("}}", 37)}),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(-1, new System.Collections.Generic.KeyValuePair<string, int>[] {
                            new System.Collections.Generic.KeyValuePair<string, int>("\0!#[]￿", 2),
                            new System.Collections.Generic.KeyValuePair<string, int>("\\\\", 4),
                            new System.Collections.Generic.KeyValuePair<string, int>("\"\"", 3)}),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(-1, new System.Collections.Generic.KeyValuePair<string, int>[] {
                            new System.Collections.Generic.KeyValuePair<string, int>("\"\"", 3),
                            new System.Collections.Generic.KeyValuePair<string, int>("\0!#[]￿", 2),
                            new System.Collections.Generic.KeyValuePair<string, int>("\\\\", 4)}),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(17, new System.Collections.Generic.KeyValuePair<string, int>[0]),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(-1, new System.Collections.Generic.KeyValuePair<string, int>[] {
                            new System.Collections.Generic.KeyValuePair<string, int>("\0￿", 5)}),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(-1, new System.Collections.Generic.KeyValuePair<string, int>[] {
                            new System.Collections.Generic.KeyValuePair<string, int>("\"\"", 3),
                            new System.Collections.Generic.KeyValuePair<string, int>("\0!#[]￿", 2),
                            new System.Collections.Generic.KeyValuePair<string, int>("\\\\", 4)}),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(-1, new System.Collections.Generic.KeyValuePair<string, int>[] {
                            new System.Collections.Generic.KeyValuePair<string, int>("\0&([]￿", 7),
                            new System.Collections.Generic.KeyValuePair<string, int>("\\\\", 9),
                            new System.Collections.Generic.KeyValuePair<string, int>("\'\'", 8)}),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(-1, new System.Collections.Generic.KeyValuePair<string, int>[] {
                            new System.Collections.Generic.KeyValuePair<string, int>("\'\'", 8),
                            new System.Collections.Generic.KeyValuePair<string, int>("\0&([]￿", 7),
                            new System.Collections.Generic.KeyValuePair<string, int>("\\\\", 9)}),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(18, new System.Collections.Generic.KeyValuePair<string, int>[0]),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(-1, new System.Collections.Generic.KeyValuePair<string, int>[] {
                            new System.Collections.Generic.KeyValuePair<string, int>("\0￿", 10)}),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(-1, new System.Collections.Generic.KeyValuePair<string, int>[] {
                            new System.Collections.Generic.KeyValuePair<string, int>("\'\'", 8),
                            new System.Collections.Generic.KeyValuePair<string, int>("\0&([]￿", 7),
                            new System.Collections.Generic.KeyValuePair<string, int>("\\\\", 9)}),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(19, new System.Collections.Generic.KeyValuePair<string, int>[] {
                            new System.Collections.Generic.KeyValuePair<string, int>("--09AZ__az", 12)}),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(19, new System.Collections.Generic.KeyValuePair<string, int>[] {
                            new System.Collections.Generic.KeyValuePair<string, int>("--09AZ__az", 12)}),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(-1, new System.Collections.Generic.KeyValuePair<string, int>[] {
                            new System.Collections.Generic.KeyValuePair<string, int>("09", 14)}),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(24, new System.Collections.Generic.KeyValuePair<string, int>[] {
                            new System.Collections.Generic.KeyValuePair<string, int>("09", 14)}),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(34, new System.Collections.Generic.KeyValuePair<string, int>[] {
                            new System.Collections.Generic.KeyValuePair<string, int>("  ", 15),
                            new System.Collections.Generic.KeyValuePair<string, int>("", 16),
                            new System.Collections.Generic.KeyValuePair<string, int>("", 17),
                            new System.Collections.Generic.KeyValuePair<string, int>("\t\t", 18),
                            new System.Collections.Generic.KeyValuePair<string, int>("\r\r", 19),
                            new System.Collections.Generic.KeyValuePair<string, int>("\n\n", 20)}),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(34, new System.Collections.Generic.KeyValuePair<string, int>[] {
                            new System.Collections.Generic.KeyValuePair<string, int>("  ", 15),
                            new System.Collections.Generic.KeyValuePair<string, int>("", 16),
                            new System.Collections.Generic.KeyValuePair<string, int>("", 17),
                            new System.Collections.Generic.KeyValuePair<string, int>("\t\t", 18),
                            new System.Collections.Generic.KeyValuePair<string, int>("\r\r", 19),
                            new System.Collections.Generic.KeyValuePair<string, int>("\n\n", 20)}),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(34, new System.Collections.Generic.KeyValuePair<string, int>[] {
                            new System.Collections.Generic.KeyValuePair<string, int>("  ", 15),
                            new System.Collections.Generic.KeyValuePair<string, int>("", 16),
                            new System.Collections.Generic.KeyValuePair<string, int>("", 17),
                            new System.Collections.Generic.KeyValuePair<string, int>("\t\t", 18),
                            new System.Collections.Generic.KeyValuePair<string, int>("\r\r", 19),
                            new System.Collections.Generic.KeyValuePair<string, int>("\n\n", 20)}),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(34, new System.Collections.Generic.KeyValuePair<string, int>[] {
                            new System.Collections.Generic.KeyValuePair<string, int>("  ", 15),
                            new System.Collections.Generic.KeyValuePair<string, int>("", 16),
                            new System.Collections.Generic.KeyValuePair<string, int>("", 17),
                            new System.Collections.Generic.KeyValuePair<string, int>("\t\t", 18),
                            new System.Collections.Generic.KeyValuePair<string, int>("\r\r", 19),
                            new System.Collections.Generic.KeyValuePair<string, int>("\n\n", 20)}),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(34, new System.Collections.Generic.KeyValuePair<string, int>[] {
                            new System.Collections.Generic.KeyValuePair<string, int>("  ", 15),
                            new System.Collections.Generic.KeyValuePair<string, int>("", 16),
                            new System.Collections.Generic.KeyValuePair<string, int>("", 17),
                            new System.Collections.Generic.KeyValuePair<string, int>("\t\t", 18),
                            new System.Collections.Generic.KeyValuePair<string, int>("\r\r", 19),
                            new System.Collections.Generic.KeyValuePair<string, int>("\n\n", 20)}),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(34, new System.Collections.Generic.KeyValuePair<string, int>[] {
                            new System.Collections.Generic.KeyValuePair<string, int>("  ", 15),
                            new System.Collections.Generic.KeyValuePair<string, int>("", 16),
                            new System.Collections.Generic.KeyValuePair<string, int>("", 17),
                            new System.Collections.Generic.KeyValuePair<string, int>("\t\t", 18),
                            new System.Collections.Generic.KeyValuePair<string, int>("\r\r", 19),
                            new System.Collections.Generic.KeyValuePair<string, int>("\n\n", 20)}),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(-1, new System.Collections.Generic.KeyValuePair<string, int>[] {
                            new System.Collections.Generic.KeyValuePair<string, int>("//", 22),
                            new System.Collections.Generic.KeyValuePair<string, int>("**", 25)}),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(-1, new System.Collections.Generic.KeyValuePair<string, int>[] {
                            new System.Collections.Generic.KeyValuePair<string, int>("\0\t￿", 23),
                            new System.Collections.Generic.KeyValuePair<string, int>("\n\n", 24)}),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(-1, new System.Collections.Generic.KeyValuePair<string, int>[] {
                            new System.Collections.Generic.KeyValuePair<string, int>("\n\n", 24),
                            new System.Collections.Generic.KeyValuePair<string, int>("\0\t￿", 23)}),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(35, new System.Collections.Generic.KeyValuePair<string, int>[0]),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(36, new System.Collections.Generic.KeyValuePair<string, int>[0]),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(29, new System.Collections.Generic.KeyValuePair<string, int>[0]),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(25, new System.Collections.Generic.KeyValuePair<string, int>[0]),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(26, new System.Collections.Generic.KeyValuePair<string, int>[0]),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(27, new System.Collections.Generic.KeyValuePair<string, int>[0]),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(28, new System.Collections.Generic.KeyValuePair<string, int>[0]),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(33, new System.Collections.Generic.KeyValuePair<string, int>[0]),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(20, new System.Collections.Generic.KeyValuePair<string, int>[0]),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(21, new System.Collections.Generic.KeyValuePair<string, int>[0]),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(22, new System.Collections.Generic.KeyValuePair<string, int>[0]),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(23, new System.Collections.Generic.KeyValuePair<string, int>[0]),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(30, new System.Collections.Generic.KeyValuePair<string, int>[0]),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(31, new System.Collections.Generic.KeyValuePair<string, int>[] {
                            new System.Collections.Generic.KeyValuePair<string, int>("++", 38)}),
                new System.Collections.Generic.KeyValuePair<int, System.Collections.Generic.KeyValuePair<string, int>[]>(32, new System.Collections.Generic.KeyValuePair<string, int>[0])};
        public EbnfTokenizer(System.Collections.Generic.IEnumerable<char> input) : 
                base(EbnfTokenizer._DfaTable, EbnfTokenizer._Symbols, EbnfTokenizer._BlockEnds, input) {
        }
    }
    public class EbnfParser : LL.LL1TableParser {
        public const int grammar = 0;
        public const int symbollist = 1;
        public const int expression = 2;
        public const int symbol = 3;
        public const int attrvalue = 4;
        public const int symbollist_ = 5;
        public const int productions = 6;
        public const int productions_ = 7;
        public const int production = 8;
        public const int production_ = 9;
        public const int expressions = 10;
        public const int expressions_ = 11;
        public const int symbol_ = 12;
        public const int attributes = 13;
        public const int attributes_ = 14;
        public const int attribute = 15;
        public const int attribute_ = 16;
        public const int literal = 17;
        public const int regex = 18;
        public const int identifier = 19;
        public const int lparen = 20;
        public const int rparen = 21;
        public const int lbracket = 22;
        public const int rbracket = 23;
        public const int integer = 24;
        public const int lt = 25;
        public const int gt = 26;
        public const int eq = 27;
        public const int semi = 28;
        public const int or = 29;
        public const int lbrace = 30;
        public const int rbrace = 31;
        public const int rbracePlus = 32;
        public const int comma = 33;
        public const int whitespace = 34;
        public const int lineComment = 35;
        public const int blockComment = 36;
        public const int _EOS = 37;
        public const int _ERROR = 38;
        static string[] _Symbols = new string[] {
                "grammar",
                "symbollist",
                "expression",
                "symbol",
                "attrvalue",
                "symbollist\'",
                "productions",
                "productions\'",
                "production",
                "production\'",
                "expressions",
                "expressions\'",
                "symbol\'",
                "attributes",
                "attributes\'",
                "attribute",
                "attribute\'",
                "literal",
                "regex",
                "identifier",
                "lparen",
                "rparen",
                "lbracket",
                "rbracket",
                "integer",
                "lt",
                "gt",
                "eq",
                "semi",
                "or",
                "lbrace",
                "rbrace",
                "rbracePlus",
                "comma",
                "whitespace",
                "lineComment",
                "blockComment",
                "#EOS",
                "#ERROR"};
        static int[][][] _ParseTable = new int[][][] {
                new int[][] {
                        null,
                        null,
                        new int[] {
                                6},
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null},
                new int[][] {
                        new int[] {
                                3,
                                5},
                        new int[] {
                                3,
                                5},
                        new int[] {
                                3,
                                5},
                        new int[] {
                                3,
                                5},
                        null,
                        new int[] {
                                3,
                                5},
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        new int[] {
                                3,
                                5},
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null},
                new int[][] {
                        new int[] {
                                1},
                        new int[] {
                                1},
                        new int[] {
                                1},
                        new int[] {
                                1},
                        new int[0],
                        new int[] {
                                1},
                        new int[0],
                        null,
                        null,
                        null,
                        null,
                        new int[0],
                        new int[0],
                        new int[] {
                                1},
                        new int[0],
                        new int[0],
                        null,
                        null,
                        null,
                        null,
                        null,
                        null},
                new int[][] {
                        new int[] {
                                17},
                        new int[] {
                                18},
                        new int[] {
                                19},
                        new int[] {
                                20,
                                10,
                                21},
                        null,
                        new int[] {
                                22,
                                10,
                                23},
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        new int[] {
                                30,
                                10,
                                12},
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null},
                new int[][] {
                        new int[] {
                                17},
                        null,
                        new int[] {
                                19},
                        null,
                        null,
                        null,
                        null,
                        new int[] {
                                24},
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null},
                new int[][] {
                        new int[] {
                                3,
                                5},
                        new int[] {
                                3,
                                5},
                        new int[] {
                                3,
                                5},
                        new int[] {
                                3,
                                5},
                        new int[0],
                        new int[] {
                                3,
                                5},
                        new int[0],
                        null,
                        null,
                        null,
                        null,
                        new int[0],
                        new int[0],
                        new int[] {
                                3,
                                5},
                        new int[0],
                        new int[0],
                        null,
                        null,
                        null,
                        null,
                        null,
                        null},
                new int[][] {
                        null,
                        null,
                        new int[] {
                                8,
                                7},
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null},
                new int[][] {
                        null,
                        null,
                        new int[] {
                                6},
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        new int[0],
                        null},
                new int[][] {
                        null,
                        null,
                        new int[] {
                                19,
                                9},
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null},
                new int[][] {
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        new int[] {
                                25,
                                13,
                                26,
                                27,
                                10,
                                28},
                        null,
                        new int[] {
                                27,
                                10,
                                28},
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null},
                new int[][] {
                        new int[] {
                                2,
                                11},
                        new int[] {
                                2,
                                11},
                        new int[] {
                                2,
                                11},
                        new int[] {
                                2,
                                11},
                        new int[] {
                                2,
                                11},
                        new int[] {
                                2,
                                11},
                        new int[] {
                                2,
                                11},
                        null,
                        null,
                        null,
                        null,
                        new int[] {
                                2,
                                11},
                        null,
                        new int[] {
                                2,
                                11},
                        new int[] {
                                2,
                                11},
                        new int[] {
                                2,
                                11},
                        null,
                        null,
                        null,
                        null,
                        null,
                        null},
                new int[][] {
                        null,
                        null,
                        null,
                        null,
                        new int[0],
                        null,
                        new int[0],
                        null,
                        null,
                        null,
                        null,
                        new int[0],
                        new int[] {
                                29,
                                10},
                        null,
                        new int[0],
                        new int[0],
                        null,
                        null,
                        null,
                        null,
                        null,
                        null},
                new int[][] {
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        new int[] {
                                31},
                        new int[] {
                                32},
                        null,
                        null,
                        null,
                        null,
                        null,
                        null},
                new int[][] {
                        null,
                        null,
                        new int[] {
                                15,
                                14},
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null},
                new int[][] {
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        new int[0],
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        new int[] {
                                33,
                                13},
                        null,
                        null,
                        null,
                        null,
                        null},
                new int[][] {
                        null,
                        null,
                        new int[] {
                                19,
                                16},
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null},
                new int[][] {
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        new int[0],
                        new int[] {
                                27,
                                4},
                        null,
                        null,
                        null,
                        null,
                        null,
                        new int[0],
                        null,
                        null,
                        null,
                        null,
                        null}};
        static int[] _InitCfg = new int[] {
                0,
                17};
        static int[] _NodeFlags = new int[] {
                0,
                1,
                0,
                0,
                0,
                1,
                1,
                1,
                0,
                1,
                1,
                1,
                1,
                1,
                1,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                2,
                2,
                0,
                0};
        static System.Collections.Generic.KeyValuePair<string, object>[][] _AttributeSets = new System.Collections.Generic.KeyValuePair<string, object>[][] {
                new System.Collections.Generic.KeyValuePair<string, object>[] {
                        new System.Collections.Generic.KeyValuePair<string, object>("start", true)},
                new System.Collections.Generic.KeyValuePair<string, object>[] {
                        new System.Collections.Generic.KeyValuePair<string, object>("collapsed", true)},
                null,
                null,
                new System.Collections.Generic.KeyValuePair<string, object>[] {
                        new System.Collections.Generic.KeyValuePair<string, object>("color", "brown")},
                new System.Collections.Generic.KeyValuePair<string, object>[] {
                        new System.Collections.Generic.KeyValuePair<string, object>("collapsed", true)},
                new System.Collections.Generic.KeyValuePair<string, object>[] {
                        new System.Collections.Generic.KeyValuePair<string, object>("collapsed", true)},
                new System.Collections.Generic.KeyValuePair<string, object>[] {
                        new System.Collections.Generic.KeyValuePair<string, object>("collapsed", true)},
                null,
                new System.Collections.Generic.KeyValuePair<string, object>[] {
                        new System.Collections.Generic.KeyValuePair<string, object>("collapsed", true)},
                new System.Collections.Generic.KeyValuePair<string, object>[] {
                        new System.Collections.Generic.KeyValuePair<string, object>("collapsed", true)},
                new System.Collections.Generic.KeyValuePair<string, object>[] {
                        new System.Collections.Generic.KeyValuePair<string, object>("collapsed", true)},
                new System.Collections.Generic.KeyValuePair<string, object>[] {
                        new System.Collections.Generic.KeyValuePair<string, object>("collapsed", true)},
                new System.Collections.Generic.KeyValuePair<string, object>[] {
                        new System.Collections.Generic.KeyValuePair<string, object>("collapsed", true)},
                new System.Collections.Generic.KeyValuePair<string, object>[] {
                        new System.Collections.Generic.KeyValuePair<string, object>("collapsed", true)},
                new System.Collections.Generic.KeyValuePair<string, object>[] {
                        new System.Collections.Generic.KeyValuePair<string, object>("color", "darkRed")},
                new System.Collections.Generic.KeyValuePair<string, object>[] {
                        new System.Collections.Generic.KeyValuePair<string, object>("collapsed", true)},
                new System.Collections.Generic.KeyValuePair<string, object>[] {
                        new System.Collections.Generic.KeyValuePair<string, object>("color", "blue")},
                new System.Collections.Generic.KeyValuePair<string, object>[] {
                        new System.Collections.Generic.KeyValuePair<string, object>("color", "purple")},
                null,
                null,
                null,
                null,
                null,
                new System.Collections.Generic.KeyValuePair<string, object>[] {
                        new System.Collections.Generic.KeyValuePair<string, object>("color", "darkBlue")},
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                new System.Collections.Generic.KeyValuePair<string, object>[] {
                        new System.Collections.Generic.KeyValuePair<string, object>("hidden", true),
                        new System.Collections.Generic.KeyValuePair<string, object>("terminal", true)},
                new System.Collections.Generic.KeyValuePair<string, object>[] {
                        new System.Collections.Generic.KeyValuePair<string, object>("hidden", true),
                        new System.Collections.Generic.KeyValuePair<string, object>("color", "green")},
                new System.Collections.Generic.KeyValuePair<string, object>[] {
                        new System.Collections.Generic.KeyValuePair<string, object>("hidden", true),
                        new System.Collections.Generic.KeyValuePair<string, object>("blockEnd", "*/"),
                        new System.Collections.Generic.KeyValuePair<string, object>("color", "green")},
                null,
                null};
        public EbnfParser(System.Collections.Generic.IEnumerable<LL.Token> tokenizer) : 
                base(EbnfParser._ParseTable, EbnfParser._InitCfg, EbnfParser._Symbols, EbnfParser._NodeFlags, EbnfParser._AttributeSets, tokenizer) {
        }
    }
}
